# Site settings
author: Brian Velez
title: Built By Brian
header-img: img/home-bg.png
email: brian.velez@blackrock.com
copyright_name: Brian Velez
description: > # this means to ignore newlines until "baseurl:"
  Projects, problems, and thoughts encountered as a new developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Bav75

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
